---
title: "ProjectDS"
author: "Afrizal Ardhi"
date: "2024-11-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidymodels)
library(tidyverse)
library(nnet)
library(dplyr)
```


#Data Gathering
```{r}
#csv obesitas
dataOb = read.csv("ObesityDataSet.csv")
head(dataOb)
#view(dataOb)
```

#Preprocessing Data
```{r}
# Hapus NA value
dataOb = na.omit(dataOb)

#Hilangkan Kolom yang tidak ingin dipakai
dataOb = dataOb %>% select(-SMOKE, -SCC, -TUE)

#Mengubah Kategorikal menjadi numerik
dataOb <- dataOb %>%
  mutate(
    Gender = as.numeric(factor(Gender, levels = c("Female", "Male"))),
    family_history_with_overweight = ifelse(family_history_with_overweight == "yes", 1, 0),
    FAVC = ifelse(FAVC == "yes", 1, 0),
    MTRANS = as.numeric(factor(MTRANS)),
    CALC = as.numeric(factor(CALC, levels = c("no", "Sometimes", "Frequently", "Always"))),
    CAEC = as.numeric(factor(CAEC, levels = c("no", "Sometimes", "Frequently", "Always")))
  )
dataOb <- dataOb %>%
  rename(FHWO = family_history_with_overweight)

head(dataOb)
```


#Split Data 80:20
```{r}
set.seed(420)
split = initial_split(dataOb, prop = 0.8)
datatrain = training(split)
datatest = testing(split)
print(datatrain)
print(datatest)
```


# Data Modelling (Multinominal Logistic Regression)
```{r}
formula = "NObeyesdad ~ ."
hasil_model = multinom(formula, data = datatrain)

summary(hasil_model)


```

# Data Testing
```{r}
#class
hasil_prediksi = predict(object = hasil_model, newdata = datatest, type = "class")
#hasil_prediksi
```


#Matrix Confussion
```{r}
table(
  Predicted = hasil_prediksi,
  Actual = datatest$NObeyesdad
)
```

#Accuration
```{r}
#paste0 buat nyatuin 2 string, dibawah angka sm persen
akurasi = paste0(round(((47+63+75 + 45 + 67 + 52 + 47)/423)*100, digit = 2), "%") 
akurasi
```


# Coba Shiny
```{r}
library(shiny)
library(bslib)
```

#Coding Web
```{r}
ui = page_fluid(
  titlePanel("Obesity Database"),
  layout_columns(
    value_box(
      title = "Man",
      value = nrow(dataOb %>% filter(Gender == "2"))
    ),
    value_box(
      title = "Woman",
      value = nrow(dataOb %>% filter(Gender == "1"))
    ),
  ),
  selectInput(
    "selectObeLevel",
    "Pilih Level Obesitas:",
    choices = unique(dataOb$NObeyesdad)
  ),
  tableOutput("tableObesity"),
  titlePanel("Uji Coba klasifikasi Level"),
  layout_columns(
    numericInput("gender", "Gender: ",value = 0),
    numericInput("age", "Age: ",value = 0),
    numericInput("height", "Height: ",value = 0),
    numericInput("weight", "Weight: ",value = 0),
    numericInput("fhwo", "FHWO: ",value = 0),
    numericInput("favc", "FAVC: ",value = 0),
    numericInput("fcvc", "FCVC: ",value = 0),
    numericInput("ncp", "NCP: ",value = 0),
    numericInput("caec", "CAEC: ",value = 0),
    numericInput("ch2o", "CH2O: ",value = 0),
    numericInput("faf", "FAF: ",value = 0),
    numericInput("calc", "CALC: ",value = 0),
    numericInput("mtrans", "MTRANS: ",value = 0),
  ),
  actionButton("tombol_klasifikasi", "Cek Level Obesitas"),
  textOutput("output_teks")
)

server = function(input, output){
  output$tableObesity = renderTable(dataOb %>% filter(NObeyesdad == input$selectObeLevel) %>% head())
  
  output$output_teks = renderText({
    input_klasifikasi = data.frame(
      Gender = input$gender,
      Age = input$age,
      Height = input$height,
      Weight = input$weight,
      FHWO = input$fhwo,
      FAVC = input$favc,
      FCVC = input$fcvc,
      NCP = input$ncp,
      CAEC = input$caec,
      CH2O = input$ch2o,
      FAF = input$faf,
      CALC = input$calc,
      MTRANS = input$mtrans
    )  
    hasil_pred = predict(
      hasil_model, 
      newdata = input_klasifikasi,
      type = "class"
    )
    paste("Predicted Obesity Level: ", hasil_pred)
  }) |> bindEvent(input$tombol_klasifikasi)
}

shinyApp(ui, server)
```


